language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang
    - os: osx
      osx_image: xcode7.1
      compiler: clang
    - os: linux
      compiler: gcc

cache: ccache

before_install:
  - brew update || true

install:
  - brew install pv || true
  - ./.travis-build.sh
