# This is a conda[1] environment file[2].
# You can use it to install some of SageMath's dependencies to speed up
# compilation times when developing SageMath.
#
# Note that currently this is only available to Linux and macOS users working
# on 64bit machines.

# To use it, you need conda with conda-forge[3] enabled. If you don't know what
# this means, install Miniconda[4] for Python 3, and run:
# > conda config --add channels conda-forge
# > conda config --set channel_priority strict 
#
# To create a new environment from this file, pick a name, say "sage" and run:
# > conda env create -n sage -f environment.yml
#
# To update your environment later if this file has changed run:
# > conda env update -n sage -f environment.yml
#
# Now you can build SageMath in this environment. To do so, enter your
# environment:
# > conda activate sage
# Change some environment variables, so SageMath's sanity checks pass:
# > export AS=`cc -print-prog-name=as`
# > export LD=`cc -print-prog-name=ld`
# Enable faster parallel builds:
# > export SAGE_NUM_THREADS=4
# > export MAKEFLAGS=-j4
# Build SageMath:
# > make 
#
# If you want to help improve this environment.yml file, add an
# `spkg-configure.m4` to your favourite package in `build/pkgs/` and add that
# package below. Since SageMath is packaged at conda-forge, all dependencies
# should be available there[5, 6].
#
# [1]: https://conda.io/en/latest/
# [2]: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
# [3]: https://conda-forge.org/
# [4]: https://docs.conda.io/en/latest/miniconda.html
# [5]: https://github.com/conda-forge/sagelib-feedstock/blob/master/recipe/meta.yaml
# [6]: https://github.com/conda-forge/sage-feedstock/blob/master/recipe/meta.yaml

name: sage
channels:
  - conda-forge
  - defaults
dependencies:
  # Optional dependencies of python3
  - openssl
  # For all the standard SageMath Packages (SPKG) that have a
  # spkg-configure.m4, we provide the corresponding conda-forge packages.
  # SPKG: arb
  - arb           2.16.*
  # SPKG: autotools
  - autoconf
  - automake
  - m4
  - gettext
  - libtool
  # SPKG: bzip2
  - bzip2         1.*
  # SPKG: cliquer
  - cliquer
  # SPKG: curl
  - curl          7.64.*
  # SPKG: eclib
  - eclib         20190226
  # SPKG: ecm
  - ecm           7.*
  # SPKG: flint
  - libflint      2.5.*
  # SPKG: freetype
  - freetype      >=2.9.1,<3
  # SPKG: gcc
  - c-compiler
  - cxx-compiler
  # SPKG: gf2x
  - gf2x          >=1.2,<2
  # SPKG: gfortran (not standard)
  - fortran-compiler
  # SPKG: git
  - git
  # SPKG: givaro
  - givaro        4.1.*
  # SPKG: glpk
  - glpk          4.65.*
  # SPKG: gsl
  - gsl
  # SPKG: iconv
  - libiconv      >=1.15,<2
  # SPKG: isl
  - isl           >=0.20
  # SPKG: lcalc
  - lcalc         1.23.*
  # SPKG: libffi
  - libffi        3.2.*
  # SPKG: libgd
  - libgd         2.2.*
  # SPKG: libpng
  - libpng        1.6.*
  # SPKG: libsemigroups
  - libsemigroups 0.6.7
  # SPKG: lrcalc
  - lrcalc        1.2.*
  # SPKG: m4ri
  - m4ri          20140914
  # SPKG: m4rie
  - m4rie         20150908
  # SPKG: mpc
  - mpc           1.1.*
  # SPKG: mpfi
  - mpfi          1.5.*
  # SPKG: mpfr
  - mpfr          4.*
  # SPKG: ncurses
  - ncurses       >=6.0,<7
  # SPKG: ntl
  - ntl           11.3.2
  # SPKG: openblas
  - openblas      >=0.3.7
  # SPKG: pari
  - pari          2.11.*
  - pari-galpol
  - pari-elldata
  - pari-nftables
  # SPKG: pari_galdata
  - pari-galdata
  # SPKG: pari_seadata_small
  - pari-seadata-small
  # SPKG: patch
  - patch
  # SPKG: pcre
  - pcre
  # SPKG: pkgconf
  - pkg-config
  # SPKG: r
  - r-base        3.6.*
  # SPKG: readline
  - readline      8.0.*
  # SPKG: rw
  - rw            0.7.*
  # SPKG: symmetrica
  - symmetrica    2.0.*
  # SPKG: xz
  - xz            5.2.*
  # SPKG: yasm
  - yasm
  # SPKG: zeromq
  - zeromq        >=4.2.5,<5
  # SPKG: zlib
  - zlib          1.2.*
