name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Submit issues to trac.sagemath.org, not here'' first issue'
        pr-message: 'Submit PRs to trac.sagemath.org, not here'' first pr'
