name: Run SAGE_ROOT/tox.ini

on: push

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_system_factor: [ubuntu-xenial, ubuntu-bionic, ubuntu-focal, debian-buster, fedora-28, fedora-31, fedora-32, archlinux-latest]
        tox_packages_factor: [minimal, standard]
    steps:
      - uses: actions/checkout@v2
      - name: Install test prerequisites
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install python-tox
      - run: |
          EXTRA_DOCKER_BUILD_ARGS="--build-arg MAKEFLAGS=\"-k V=0\"" tox -e docker-${{ matrix.tox_system_factor }}-${{ matrix.tox_packages_factor }}
      - name: Copy logs from the build container
        run: |
          mkdir -p artifacts; for CONTAINER in `docker ps -q -a`; if docker cp $CONTAINER:/sage/config.log artifacts/ || docker cp $CONTAINER:/sage/logs artifacts/; then break; fi; done
        if: always()
      - uses: actions/upload-artifact@v1
        with:
          path: artifacts
          name: logs-docker-${{ matrix.tox_system_factor }}-${{ matrix.tox_packages_factor }}
        if: always()
      - name: Print out logs for immediate inspection
        run: |
          find artifacts/ -name build.log -prune -o -type f -exec sh -c 'if tail -20 "{}" 2>/dev/null | grep "^Error" &>/dev/null; then echo ::error file={}; cat {} ; fi; done
        if: always()
