name: Run SAGE_ROOT/tox.ini

on: push

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_system_factor: [ubuntu-xenial, ubuntu-bionic, ubuntu-focal, debian-buster, fedora-28, fedora-31, fedora-32, archlinux-latest]
        tox_packages_factor: [minimal, standard]
    steps:
    - uses: actions/checkout@v1
    - run: |
        tox -e docker-${{ matrix.tox_system_factor }}-${{ matrix.tox_packages_factor }}
