name: Run SAGE_ROOT/tox.ini

on: push

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_system_factor: [ubuntu-xenial, ubuntu-bionic, ubuntu-focal, debian-buster, fedora-28, fedora-31, fedora-32, archlinux-latest, conda-forge, conda-anaconda3]
        tox_packages_factor: [minimal, standard]
    steps:
      - uses: actions/checkout@v2
      - name: Install test prerequisites
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install python-tox
      - run: |
          EXTRA_DOCKER_BUILD_ARGS="--build-arg MAKEFLAGS=\"-k V=0\"" tox -e docker-${{ matrix.tox_system_factor }}-${{ matrix.tox_packages_factor }}
      - name: Copy logs from the build container
        run: |
          mkdir -p artifacts; cp .tox/*/Dockerfile artifacts/; for CONTAINER in `docker ps -q -a`; do for ARTIFACT in  /sage/config.log /sage/logs/pkgs/; do docker cp $CONTAINER:$ARTIFACT artifacts/ && HAVE_LOG=1; done; if [ -n "$HAVE_LOG" ]; then break; fi; done
        if: always()
      - uses: actions/upload-artifact@v1
        with:
          path: artifacts
          name: logs-docker-${{ matrix.tox_system_factor }}-${{ matrix.tox_packages_factor }}
        if: always()
      - name: Print out logs for immediate inspection
        run: |
          find artifacts/ -type f -exec sh -c 'if tail -20 "{}" 2>/dev/null | grep "^Error" &>/dev/null; then echo :":"error file={}:":" ==== LOG FILE FOLLOWS ====; cat {} ; fi' \;
        if: always()
