name: Run SAGE_ROOT/tox.ini

on: push

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_system_factor: [ubuntu-xenial, ubuntu-bionic, ubuntu-focal, debian-buster, fedora-28, fedora-31, fedora-32, archlinux-latest]
        tox_packages_factor: [minimal, standard]
    steps:
      - uses: actions/checkout@v2
      - name: Install test prerequisites
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install python-tox
      - run: |
          EXTRA_DOCKER_BUILD_ARGS="--build-arg MAKEFLAGS=\"-k V=0\"" tox -e docker-${{ matrix.tox_system_factor }}-${{ matrix.tox_packages_factor }}
      - name: Copy logs from the build container
        run: |
          CONTAINER=`docker ps -q -a | head -n1`; mkdir -p artifacts; docker cp $CONTAINER:/sage/config.log artifacts/; docker cp $CONTAINER:/sage/logs artifacts/
        if: always()
      - uses: actions/upload-artifact@v1
        with:
          path: artifacts
          name: artifacts
        if: always()
